---
- name: Install Nginx and create vhosts
  hosts: webservers
  remote_user: runner
  become: true
  become_method: sudo

  vars:
    nginx_sites:
    - "etis.com"
    - "fizfak.ru"
    - "mehmat.ru"

  roles:
  - nginx-vhosts