---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: Get Nginx version
  ansible.builtin.shell: nginx -v 2>&1 | jq -R 'split(" ")' | jq -r '.[2]'
  register: nginx_version

- name: Debug message
  ansible.builtin.debug:
    msg: "Nginx version:{{ nginx_version.stdout }}"